### ISSUE TITLE
Taro v3.2.12 使用ErrorRetryMiddleware 报错

### ISSUE THREAD

**Issue by etoup** [xdoer/PreQuest#27]
prequest
  .use(cacheMiddleware.run)
  .use(errorRetryMiddleware.run)
  .use(lockMiddleware)
  .use(parseResponse)

使用use(errorRetryMiddleware.run)报错信息如下：

./node_modules/@prequest/error-retry/dist/errorretrymiddleware.cjs.development.js 28:34
Module parse failed: Unexpected token (28:34)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
|     return {
>       retryCount: opt.retryCount ?? (ctx.request.retryCount || ((_this$opt = this.opt) == null ? void 0 : _this$opt.retryCount) || 1),
|       retryControl: ctx.request.retryControl || ((_this$opt2 = this.opt) == null ? void 0 : _this$opt2.retryControl) || defaultRetryControl
|     };

./node_modules/@prequest/error-retry/dist/errorretrymiddleware.cjs.development.js 28:34
Module parse failed: Unexpected token (28:34)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
|     return {
>       retryCount: opt.retryCount ?? (ctx.request.retryCount || ((_this$opt = this.opt) == null ? void 0 : _this$opt.retryCount) || 1),
|       retryControl: ctx.request.retryControl || ((_this$opt2 = this.opt) == null ? void 0 : _this$opt2.retryControl) || defaultRetryControl
|     };
 @ ./node_modules/@prequest/error-retry/dist/index.js 7:19-71
 @ ./src/utils/error-retry.ts
 @ ./src/utils/http.ts
 @ ./node_modules/babel-loader/lib!./src/pages/common/index.tsx
 @ ./src/pages/common/index.tsx

**Comment by xdoer** [comment]
@etoup 打的包默认都是 ES6 的代码，所以出现了这种情况。你可以在 config 中添加如下配置:
```bash
const config = {
   // ...some code
   mini: {
     // ...some code
    compile: {
      include: [
        (modulePath) => modulePath.indexOf("@prequest") >= 0,
      ],
    },
  }
}
```
Taro 配置[参考](https://nervjs.github.io/taro/docs/config-detail#minicompile)

**Comment by etoup** [comment]
好的，问题解决了，谢谢
