### ISSUE TITLE
Module '"@prequest/lock"' has no exported member 'createLockWrapper'. 

### ISSUE THREAD

**Issue by kevin0713** [xdoer/PreQuest#28]
![1624355402846](https://user-images.githubusercontent.com/13919688/122903907-6e059180-d382-11eb-92f5-185c4b012d67.jpg)

Module '"@prequest/lock"' has no exported member 'createLockWrapper'. 

文档是否没有及时更新

**Comment by xdoer** [comment]
不好意思，忘记更新文档了。现在改为了[默认导出](https://pre-quest.vercel.app/#/lock)

**Comment by kevin0713** [comment]
@xdoer 非常感谢，及时更新文档。

**Comment by kevin0713** [comment]
> 我正在使用Taro开发小程序  respones= await  request('xxx') 如何在try catch 里捕获到业务errorcode,我在拦截器里使用Promise.reject(data) 并没有起作用。



import { PreQuest, create } from '@prequest/miniprogram'
import { InterceptorMiddleware } from '@prequest/interceptor'
import Taro from '@tarojs/taro'

 const interceptor = new InterceptorMiddleware()
 const prequest:any = create(Taro.request, opt) 

 interceptor.response.use(async(response:any)=>{

      const data=response.data


      switch (data.errorcode){
          case 0:
            return data
          default:

           return  Promise.reject(data)
      }
  },
  error => {
   
    console.log('parse response fail', error)

  }
  )

export default prequest

**Comment by xdoer** [comment]
拦截器里抛异常不要使用Promise.reject，直接throw data 就可以.

**Comment by kevin0713** [comment]
不好意思，可能我没有把问题描述清楚。

import { prequest } from './prequest'

async function getData() {
  try {

    const res = await prequest('/api', opt)

  } catch (e) {
    
   // 我如何捕捉到拦截器中返回的 errorcode !==0 的业务data？
    console.log(e)
  }
}

**Comment by xdoer** [comment]
@kevin0713 在拦截器的 error 回调函数里，再把错误抛出去即可。

**Comment by xdoer** [comment]
待会儿我补个 demo

**Comment by kevin0713** [comment]
@xdoer Many thanks.:smile:

**Comment by xdoer** [comment]
@kevin0713 issuses 先关闭了，有问题再提一个 issuses 或者加QQ群: 168837667 聊一下
