### ISSUE TITLE
Taro v3.2.10 请求锁报错

### ISSUE THREAD

**Issue by liwenjun95** [xdoer/PreQuest#29]
![图片](https://user-images.githubusercontent.com/25291272/124856018-6a0d7c80-dfdc-11eb-98b7-159391431854.png)
![图片](https://user-images.githubusercontent.com/25291272/124856079-81e50080-dfdc-11eb-823a-abbe450d4678.png)
请求token接口获取到token，赋值给ctx.request.headers['Authorization'] 时报Unhandled promise rejection TypeError: Cannot set property 'Authorization' of undefined

**Comment by xdoer** [comment]
改成这样
```tsx
ctx.request.headers = ctx.request.headers || {}
ctx.request.headers['Authorization'] = 'Bearer' + 'xxx'
```

**Comment by liwenjun95** [comment]
> 
> 
> 改成这样
> 
> ```tsx
> ctx.request.headers = ctx.request.headers || {}
> ctx.request.headers['Authorization'] = 'Bearer' + 'xxx'
> ```

谢谢 大佬

> 
> 
> 改成这样
> 
> ```tsx
> ctx.request.headers = ctx.request.headers || {}
> ctx.request.headers['Authorization'] = 'Bearer' + 'xxx'
> ```

![图片](https://user-images.githubusercontent.com/25291272/124857953-c45c0c80-dfdf-11eb-9726-e1b4745ef53c.png)
![图片](https://user-images.githubusercontent.com/25291272/124858021-e2297180-dfdf-11eb-965a-5126cd9b3b07.png)
请求头没Authorization

**Comment by xdoer** [comment]
然后你看一下这里的文档：[请求锁](https://pre-quest.vercel.app/#/lock)。。在一些平台上发的文档比较旧。。

我看你的截图，wrapper 函数第二个参数是不需要传的
```tsx
prequest.use(async (ctx, next) => {
  if (ctx.request.skipTokenCheck) return next()

  const token = await wrapper(() => prequest('/token', { skipTokenCheck: true }).then(res => res.data))
  ctx.request.headers = ctx.request.headers || {}
  ctx.request.headers['Authorization'] = `bearer ${token}`
  await next()
})
```

**Comment by xdoer** [comment]
> > 改成这样
> > ```tsx
> > ctx.request.headers = ctx.request.headers || {}
> > ctx.request.headers['Authorization'] = 'Bearer' + 'xxx'
> > ```
> 
> 谢谢 大佬
> 
> > 改成这样
> > ```tsx
> > ctx.request.headers = ctx.request.headers || {}
> > ctx.request.headers['Authorization'] = 'Bearer' + 'xxx'
> > ```
> 
> ![图片](https://user-images.githubusercontent.com/25291272/124857953-c45c0c80-dfdf-11eb-9726-e1b4745ef53c.png)
> ![图片](https://user-images.githubusercontent.com/25291272/124858021-e2297180-dfdf-11eb-965a-5126cd9b3b07.png)
> 请求头没Authorization

小程序里是 header, 不是 headers
![image](https://user-images.githubusercontent.com/22864183/124858475-b2c73480-dfe0-11eb-99c3-86350dc48797.png)

**Comment by xdoer** [comment]
小程序参数列表，看一下这个[文档:https://pre-quest.vercel.app/#/miniprogram](https://pre-quest.vercel.app/#/miniprogram)

**Comment by liwenjun95** [comment]
> 
> 
> 然后你看一下这里的文档：[请求锁](https://pre-quest.vercel.app/#/lock)。。在一些平台上发的文档比较旧。。
> 
> 我看你的截图，wrapper 函数第二个参数是不需要传的
> 
> ```tsx
> prequest.use(async (ctx, next) => {
>   if (ctx.request.skipTokenCheck) return next()
> 
>   const token = await wrapper(() => prequest('/token', { skipTokenCheck: true }).then(res => res.data))
>   ctx.request.headers = ctx.request.headers || {}
>   ctx.request.headers['Authorization'] = `bearer ${token}`
>   await next()
> })
> ```


> 
> 
> > > 改成这样
> > > ```tsx
> > > ctx.request.headers = ctx.request.headers || {}
> > > ctx.request.headers['Authorization'] = 'Bearer' + 'xxx'
> > > ```
> > 
> > 
> > 谢谢 大佬
> > > 改成这样
> > > ```tsx
> > > ctx.request.headers = ctx.request.headers || {}
> > > ctx.request.headers['Authorization'] = 'Bearer' + 'xxx'
> > > ```
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/25291272/124857953-c45c0c80-dfdf-11eb-9726-e1b4745ef53c.png)
> > ![图片](https://user-images.githubusercontent.com/25291272/124858021-e2297180-dfdf-11eb-965a-5126cd9b3b07.png)
> > 请求头没Authorization
> 
> 小程序里是 header, 不是 headers
> ![image](https://user-images.githubusercontent.com/22864183/124858475-b2c73480-dfe0-11eb-99c3-86350dc48797.png)


OK了 谢谢 大佬指导！！
