### ISSUE TITLE
文档不详细

### ISSUE THREAD

**Issue by 1404369980** [xdoer/PreQuest#30]
大哥，能不能详细写下入门文档，看了文档，我发一个post请求都要猜，method参数放在哪里

**Comment by xdoer** [comment]
> 大哥，能不能详细写下入门文档，看了文档，我发一个post请求都要猜，method参数放在哪里

Ok，晚点我再补一下，文档里对这个有说明，发请求和是axios类似的
https://pre-quest.vercel.app/#/usage

**Comment by xdoer** [comment]
文档可以打开吗？

**Comment by 1404369980** [comment]
哦哦，最近在开发小程序项目




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xdoer/PreQuest"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月23日(星期五) 中午1:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xdoer/PreQuest] 文档不详细 (#30)





  
大哥，能不能详细写下入门文档，看了文档，我发一个post请求都要猜，method参数放在哪里
  
Ok，晚点我再补一下，文档里对这个有说明，发请求和是axios类似的
 https://pre-quest.vercel.app/#/usage
