### ISSUE TITLE
错误重试中间件貌似次数限制未起作用??

### ISSUE THREAD

**Issue by itmanyong** [xdoer/PreQuest#31]
情况：创建prerequest实例，只挂载错误重试中间件，中间件具体配置如下，但是请求之后貌似一直再重试。
![image](https://user-images.githubusercontent.com/53500371/128592994-fc6f67bd-9134-4103-8a32-040bdf2e7a33.png)
![image](https://user-images.githubusercontent.com/53500371/128593016-8d978f2c-a54b-419f-9545-cac861b24863.png)

**Comment by xdoer** [comment]
能弄个仓库，复现一下吗？

**Comment by itmanyong** [comment]
这有个简单的示例，无限循环请求。https://codesandbox.io/s/quiet-violet-duepv?file=/src/App.js

**Comment by xdoer** [comment]
感谢，找到原因所在了，等我修复一下，发一个版本。

**Comment by xdoer** [comment]
@itmanyong 已经修复了，要重新装一下安装包，或者你直接在你代码里，新建个文件，把[代码https://github.com/xdoer/PreQuest/blob/main/packages/error-retry/src/index.ts](https://github.com/xdoer/PreQuest/blob/main/packages/error-retry/src/index.ts)粘贴过去用

**Comment by itmanyong** [comment]
版本："@prequest/interceptor": "^1.0.3"、"@prequest/miniprogram": "^1.0.3"
情况：按照文档例子，响应拦截器貌似拦截不了,成功的请求拦截其中完全拦截不了，仿佛没有进入。如下图所示，请求成功了，但没有进入响应拦截。甚至在请求完成后我也无法拿到数据。
![image](https://user-images.githubusercontent.com/53500371/128597117-d804d71c-df0d-4c5d-a054-e4ef9456aa4e.png)
![image](https://user-images.githubusercontent.com/53500371/128597125-197c117f-710b-44d7-a3ef-7140dbde0eaa.png)
![image](https://user-images.githubusercontent.com/53500371/128597134-31e69462-ace3-4e8b-8eac-f5060286c89b.png)
![image](https://user-images.githubusercontent.com/53500371/128597135-2bb6263d-a5da-46da-a918-7333df0fcdd1.png)
![image](https://user-images.githubusercontent.com/53500371/128597218-599cabf7-c068-437e-a9d1-312b2e1ce413.png)

**Comment by xdoer** [comment]
拦截器有注册到中间件吗？

**Comment by itmanyong** [comment]
令我无法理解的是：同样是创建的实例同一个接口，一个可以拿到数据而封装导出的缺无法拿到数据！！！
1.封装实例，直接导出，不做任何中间件处理
![image](https://user-images.githubusercontent.com/53500371/128597420-396976a1-d616-4759-8f11-17bf8e8f2f06.png)
![image](https://user-images.githubusercontent.com/53500371/128597426-ef8763eb-75e4-499e-95c4-402c04d8036e.png)
![image](https://user-images.githubusercontent.com/53500371/128597431-8f38cefb-3299-4bff-8f27-bc7a5df340eb.png)
![image](https://user-images.githubusercontent.com/53500371/128597440-7984e241-64c7-4769-a327-53c8022242f0.png)

**Comment by itmanyong** [comment]
> 拦截器有注册到中间件吗？
拦截器已注册到中间件，控制台也打印了请求拦截的配置。就是响应拦截未有响应。

**Comment by xdoer** [comment]
我这边测试结果是没问题的。

测试过程如下:
```ts
<!---demo.ts---->

import { create } from '@prequest/miniprogram'
import Taro from '@tarojs/taro'

const prequestInstance = create(Taro.request, {
  baseURL: 'http://localhost:8000'
})

export default prequestInstance

```

页面文件
```ts
import { View } from '@tarojs/components'
import preInstance from '@common/demo'
import { create } from '@prequest/miniprogram'
import Taro from '@tarojs/taro'

export default function () {

  function common() {
    preInstance.post('/token').then(res => {
      console.log('查看响应1', res)
    })
    create(Taro.request).post('http://localhost:8000/token').then(res => {
      console.log('查看响应2', res)
    })
  }

  return (
    <View>
      <View onClick={common}>普通请求</View>
    </View>
  )
}
```

响应如下:
![image](https://user-images.githubusercontent.com/22864183/128598093-a2835643-5200-4fe6-a4f1-35ea3314533f.png)

**Comment by itmanyong** [comment]
> 我这边测试结果是没问题的。
> 
> 测试过程如下:
> 
> ```ts
> 
> 
> import { create } from '@prequest/miniprogram'
> import Taro from '@tarojs/taro'
> 
> const prequestInstance = create(Taro.request, {
>   baseURL: 'http://localhost:8000'
> })
> 
> export default prequestInstance
> ```
> 
> 页面文件
> 
> ```ts
> import { View } from '@tarojs/components'
> import preInstance from '@common/demo'
> import { create } from '@prequest/miniprogram'
> import Taro from '@tarojs/taro'
> 
> export default function () {
> 
>   function common() {
>     preInstance.post('/token').then(res => {
>       console.log('查看响应1', res)
>     })
>     create(Taro.request).post('http://localhost:8000/token').then(res => {
>       console.log('查看响应2', res)
>     })
>   }
> 
>   return (
>     <View>
>       <View onClick={common}>普通请求</View>
>     </View>
>   )
> }
> ```
> 
> 响应如下:
> ![image](https://user-images.githubusercontent.com/22864183/128598093-a2835643-5200-4fe6-a4f1-35ea3314533f.png)

我尝试了你的例子没有问题，加上responseType:json之后就不可以； 你试一下呢，我反复尝试了几次，确实是注销； responseType设置就可以一致，貌似上面的响应拦截也是由于这个导致

**Comment by xdoer** [comment]
Taro 的 [responseType 不支持 json](https://taro-docs.jd.com/taro/docs/apis/network/request/request#responsetype)，传了导致响应不了，用原始的 Taro.request 请求也一样。

**Comment by itmanyong** [comment]
> Taro 的 [responseType 不支持 json](https://taro-docs.jd.com/taro/docs/apis/network/request/request#responsetype)，传了导致响应不了，用原始的 Taro.request 请求也一样。

感觉可以兼容一下

**Comment by xdoer** [comment]
请求库层面兼容不了，因为本质上是通过 [success 和 fail 回调函数](https://github.com/xdoer/PreQuest/blob/main/packages/miniprogram/src/adapter.ts)，来判断请求成功与否，如果 Taro.request 没有响应，请求库层面就会认为一直处于请求的过程中。。这个只能给 Taro 提 RP 了
