### ISSUE TITLE
还是uniapp 缓存的问题,

### ISSUE THREAD

**Issue by ayhome** [xdoer/PreQuest#35]
缓存控制器这样来写

cacheKernel() {  
    return {  
      get:function(key) {  
        let resq = uni.getStorageSync(key)  
        if(!resq) return false;  
        return resq;  
      },  
      // set: uni.setStorageSync,  
      set: function(key,resq){  
        uni.setStorageSync(key,resq);  
      },  
      delete: function(key){  
        return uni.removeStorageSync(key)  
      }  
    }  
  }, 

但是返回的是空
`
prequest.post(url, args).then(res => {    
    console.log(res); // {}  这里是空  
    
  }).then(res => {  
      
  })  
`

**Comment by xdoer** [comment]
非常抱歉，源代码里有个 Bug，一时半会儿还解决不了。。你这里具体需求是什么？我可以帮你先出出主意

**Comment by ayhome** [comment]
> 非常抱歉，源代码里有个 Bug，一时半会儿还解决不了。。你这里具体需求是什么？我可以帮你先出出主意

不急，等你修复再更新，我自己也有折中办法，不过你框架刚好符合我需求，

**Comment by xdoer** [comment]
Bug 是由 [中间件里的 return](https://github.com/xdoer/PreQuest/blob/9eb38d8beaae33ecb16c6359eb355f9ebee94273/packages/cache/src/index.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L45) 引起的，根据目前的项目架构，缓存的功能只能做到 [adapter](https://github.com/xdoer/PreQuest/blob/9eb38d8beaae33ecb16c6359eb355f9ebee94273/packages/miniprogram/src/adapter.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L14) 的 request 请求方法前，在这里使用缓存取数据，然后进行 promise 的 resolve。。你可以把 @prequest/miniprogram 的源码拷贝到你项目里，自己尝试改改

**Comment by xdoer** [comment]
想到了一个办法处理缓存 https://pre-quest.vercel.app/#/cache
