### ISSUE TITLE
await 如何获取promise rejection ? 

### ISSUE THREAD

**Issue by 23233** [xdoer/PreQuest#36]
### 代码示例

```
// 发起请求
const req = await req.get("any")
// 如果断网的情况下 永远不会进入到下一步
if (req.statusCode === 200) { .... }

```

### 想要的结果

能够永远获取response 不管是成功与失败 能够走到最后而不会被半途break !

### 基本环境
* 微信小程序 taro react

**Comment by xdoer** [comment]
@23233 晚上回去看一下，应该不会出现这样的情况，因为小程序默认会超时报错

**Comment by xdoer** [comment]
经过验证，没发现你这样的问题。
![image](https://user-images.githubusercontent.com/22864183/146635944-74ef8649-126f-442e-bc50-337ee4343256.png)
