### ISSUE TITLE
ios 9 : ReferenceError: Can't find variable: Proxy __ERROR 

### ISSUE THREAD

**Issue by lzlv312** [xdoer/PreQuest#39]
项目要求要兼容ios9和安卓5，测试了下居然报错，请避免只使用 new Proxy，这对低版本系统不友好，谢谢

**Comment by SplendorJiang** [comment]
不知道对你有没有帮助 https://pre-quest.vercel.app/#/compatible

**Comment by lzlv312** [comment]
没用的，Proxy 这个api不会被转换，单纯的引入 proxy 垫片测试也不行

**Comment by lzlv312** [comment]
@SplendorJiang 没用的，Proxy 这个api不会被转换，单纯的引入 proxy 垫片测试 use 时会报错

**Comment by xdoer** [comment]
proxy已移除:https://github.com/xdoer/PreQuest/blob/da1245788a24691dbb0b324e00bedb776675c964/packages/core/src/index.ts#L68

**Comment by lzlv312** [comment]
@xdoer 好的，可以了，问题解决了，还以为需要弃用了，感谢更新，你真棒！那，我的两个问题现在可以关闭了。

**Comment by xdoer** [comment]
之前没时间处理这个问题，所以在五一看一下。

这个库不会弃用的，我自己也在用。。

这两个 issues 先关了吧，遇到问题再反馈
