### ISSUE TITLE
about xhr responseType...

### ISSUE THREAD

**Issue by lzlv312** [xdoer/PreQuest#40]
xhr.esm.js:19 Uncaught DOMException: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'blob').

xhr.esm.js:19 Uncaught DOMException: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'arraybuffer').

我该如何使用它来进行二进制数据的下载？？？

**Comment by lzlv312** [comment]
另外，若请求头仅设置了 Content-Type （不区分大小写） 的值，则不应该受到helper中 requestType 的逻辑影响，应以设置的Content-Type 为优先，现在的情况是参数被错误的序列化了。

**Comment by lzlv312** [comment]
或许可以考虑去掉requestType，以保持和小程序端的一个统一，而且用JSON将用户参数转为字符串，可能并不是一个好主意，从某些角度来讲。

**Comment by xdoer** [comment]
可以的，明天我改造一下，把 fetch 和 xhr 里的都去掉吧。。

**Comment by xdoer** [comment]
已经去掉了，1.5.0

**Comment by lzlv312** [comment]
啊这，兄弟响应速度一直都好快，我测试了下，我想说抱歉，原谅我上面最后多那一嘴，我主要说两个问题：
1、responseType: 'blob' 无法得到预期，arraybuffer 也一样
2、requestType 的存在影响了Content-Type 的设置

第1点，我下面有个代码的图，我保证它在axios下是正常工作的。
第2点，这个可以去掉也可以改优先级，不过为了统一，还是去掉吧，毕竟小程序和axios都没这个东西，然后我又找了下uniapp和微信小程序文档，对于基本的两种类型还是需要做处理的，但是是根据 Content-Type 来模糊判断的，且有默认值，具体我下面上图。另外由于JSON.stringify的特点，会丢失无效值的字段（比如undefined，虽然无效的值不应该存在，但是丢失字段对于后端接收来说就是大问题了），以及它的性能，简单粗暴可以用它，或者使用第三方更好的实现，如：https://github.com/dbl0null/slow-json-stringify （这个可以只看看）

所以这次我说清楚了吗？
![剪贴板图片](https://user-images.githubusercontent.com/36726139/174441640-6a3d6cbf-7325-4707-9759-1a0c3635c6a6.jpg)
![剪贴板图片 (1)](https://user-images.githubusercontent.com/36726139/174441643-85e6c375-b600-46fe-9de8-465acc1bf2bd.jpg)
![剪贴板图片 (2)](https://user-images.githubusercontent.com/36726139/174441646-8a272932-0587-40f5-825a-832e695d2d23.jpg)
![剪贴板图片 (3)](https://user-images.githubusercontent.com/36726139/174441648-7eb544dd-d232-4cee-8cc4-25d7dd34b074.jpg)

**Comment by xdoer** [comment]
1. 帮忙验证一下，在 node_modules 的 @prequest/xhr 包里改成下面这样，能否正常运行
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/22864183/174442420-7ed57e19-f0ab-4b33-888c-235e5bf92015.png">
2. requestType 先去掉了，感觉这不是个很好的设计

**Comment by lzlv312** [comment]
测试了，确实是这个问题，我目前项目用到的请求方式大概看了下，都工作正常了
那就剩下那个 data 数据了，根据上次最后的两张图 uniapp/小程序 的 data数据说明，做下优化？
但是他只说了 get和post下，其他请求方式如 put ， delete 等 是否一样有效？

**Comment by lzlv312** [comment]
补下图：
![剪贴板图片](https://user-images.githubusercontent.com/36726139/174465044-87159bd0-c9df-4479-917c-75da3fa9d26a.jpg)

![剪贴板图片 (1)](https://user-images.githubusercontent.com/36726139/174465035-32533e9b-86dc-4766-b66b-84f9472ddda1.jpg)

**Comment by xdoer** [comment]
我没太明白你的意思，是说 xhr 这个和小程序保持一致，处理 request params 或者 body 吗？

实际我不打算再维护 xhr、fetch 和 node 这三个库了，xhr 和 node 的源码是直接抄的 axios 的，fetch 参考了 umi-request。 维护起来较困难。
后面我会在文档里写清楚，推荐直接用 axios 构造个 adapter，这样可以兼具 axios 和 prequest 的能力。

1. https://pre-quest.vercel.app/#/work-with-axios
2. https://github.com/xdoer/PreQuest/blob/main/examples/web/src/Axios.tsx

**Comment by lzlv312** [comment]
啊这，先别啊，responseType改了后，应该就差一步优化了，不要放弃！
我的意思就是说 xhr 这个和小程序保持一致，按照他们文档描述的规则 处理 request params 或者 body ，我测试了下uniapp 的 put 和 delete 请求，实际就是根据 Content-Type 的值来进行处理的，不仅仅是get和post才处理。
![剪贴板图片](https://user-images.githubusercontent.com/36726139/174477536-61b40605-7b91-48c9-a39a-5af2b435b76e.jpg)

至于node，fetch我没用到也就没看，是不是需要改。

**Comment by lzlv312** [comment]
[index.zip](https://github.com/xdoer/PreQuest/files/8963746/index.zip)
我改了下，测试在我的项目中工作正常，你看看有什么地方需要修改的。 @xdoer
