### ISSUE TITLE
createAsyncPromise   @xdoer/x 只在dev分支才有这个静态方法，已发版的还没有这个静态方法

### ISSUE THREAD

**Issue by hhch** [xdoer/PreQuest#42]
createAsyncPromise   @xdoer/x 只在dev分支才有这个静态方法，已发版的还没有这个静态方法

但是已发版的 lock 包却引用了这个方法

导致报错

还请麻烦更新下@xdoer/x 包呢

**Comment by xdoer** [comment]
已修复 1.5.2

**Comment by lzlv312** [comment]
![image](https://user-images.githubusercontent.com/36726139/178142852-17c75aa7-a3db-4fed-be22-84455c55fafb.png)
确定吗？ @xdoer

**Comment by xdoer** [comment]
@lzlv312 完整的报错能截一下吗？你这个问题看样子是 babel 不支持编译这个语法报的错，需要在 babel 里调整一下相关配置

**Comment by xdoer** [comment]
装一下 @babel/preset-env ，在 babel 的配置文件中配一下再运行试试 @lzlv312

**Comment by lzlv312** [comment]
![image](https://user-images.githubusercontent.com/36726139/178143350-f4331edd-f566-42f5-9e36-d0142b31a4ca.png)
![image](https://user-images.githubusercontent.com/36726139/178143372-8bd201cd-416b-4ef8-940d-00c5a6698a11.png)
我这个配置原本在项目中跑得好好的呀？

**Comment by lzlv312** [comment]
@xdoer

**Comment by xdoer** [comment]
装一下这个 @babel/plugin-proposal-class-properties

**Comment by lzlv312** [comment]
@xdoer 可以了

**Comment by hhch** [comment]
> 已修复 1.5.2

谢谢
