### ISSUE TITLE
export declare type RetryControl = (opt: PQRequest, err: PQError) => boolean;

### ISSUE THREAD

**Issue by hhch** [xdoer/PreQuest#43]
这个
export declare type RetryControl = (opt: PQRequest, err: PQError) => boolean;
按道理应该是 
export declare type RetryControl = (opt: PQRequest, err: PQError) => Promise\<boolean\>;

见调用的代码
const control = await options.retryControl(ctx.request, e);

**Comment by xdoer** [comment]
1.5.2 已修复

**Comment by hhch** [comment]
> 1.5.2 已修复

谢谢
