### ISSUE TITLE
类型不全

### ISSUE THREAD

**Issue by aalexlin** [xdoer/PreQuest#47]
![image](https://user-images.githubusercontent.com/6197922/182996523-b7c936b8-741b-4d40-8a02-4cb5f0cb6ab8.png)

![image](https://user-images.githubusercontent.com/6197922/182996452-7d2d0940-f56c-42f7-bbba-a04b59436d3f.png)

**Comment by xdoer** [comment]
手动装一下 @prequest/types 这个包
